#!/bin/sh

### BEGIN INIT INFO
# Provides:          mailman-api
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mailman API
# Description:       Starts and stops the mailman-api daemon.
### END INIT INFO

# Author: Antonio Terceiro <terceiro@softwarelivre.org>

DESC="Mailman REST API"
NAME=mailman-api
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/${NAME}.pid

do_start() {
    start-stop-daemon --start --exec $DAEMON --pidfile $PIDFILE --make-pidfile --name $NAME --background
}

do_stop() {
    start-stop-daemon --stop --name $NAME --pidfile $PIDFILE
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	do_stop
        do_start
	;;
  *)
	echo "usage: $0 start|stop|restart"
	exit 3
	;;
esac
exit 0
